# Cloud Build Config for Frontend
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vwl-rl-frontend'
      - '-f'
      - 'frontend/Dockerfile'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/vwl-rl-frontend'
