# Cloud Build Config for Backend
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vwl-rl-backend'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/vwl-rl-backend'
