# Cloud Build for Training Job
# Manually triggered for RL model training

steps:
  # Build Training Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vwl-rl-training:latest'
      - '-f'
      - 'train/Dockerfile.training'
      - '.'

  # Push Training Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vwl-rl-training:latest']

  # Submit Training Job to Cloud Run Jobs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs create rl-training-job \
          --image gcr.io/$PROJECT_ID/vwl-rl-training:latest \
          --region europe-west1 \
          --memory 16Gi \
          --cpu 8 \
          --task-timeout 24h \
          --set-env-vars GCS_BUCKET=$PROJECT_ID-ml-models,PUBSUB_TOPIC=projects/$PROJECT_ID/topics/training-events-dev \
          --execute-now

images:
  - 'gcr.io/$PROJECT_ID/vwl-rl-training:latest'

timeout: '3600s'
